project:
  type: website
  output-dir: ../nickproth.github.io
website:
  title: "Nicks Sports blog"
  description: "i hope this works."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nickproth
      - icon: twitter
        href: https://twitter.com/nproth44
  favicon: logo.png
  
format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: styles.css

editor: visual

execute:
  freeze: auto
